---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "metabuli_add"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::metabuli=1.0.5"
